#!/bin/sh

RED="\033[1;31m"
GREEN="\033[1;32m"
NC="\033[0m"

LINTER_EXIT_CODE=1
ALL_TS_FILES=$(git diff --cached --diff-filter=d --name-only | grep .ts$)
ALL_TSX_FILES=$(git diff --cached --diff-filter=d --name-only | grep .tsx$)
./node_modules/.bin/eslint $ALL_TS_FILES --quiet --fix && ./node_modules/.bin/eslint $ALL_TSX_FILES --quiet --fix
LINTER_EXIT_CODE=$?

git add -f $ALL_TS_FILES $ALL_TSX_FILES

if [ $LINTER_EXIT_CODE -ne 0 ]
then
  echo "${RED} ❌ Errors have occurred in linter ( ͡ಥ ͜ʖ ͡ಥ)${NC}"
  exit 1
else
  echo "${GREEN} ✔ Linter did not find any errors [̲̅$̲̅(̲̅ ͡° ͜ʖ ͡°̲̅)̲̅$̲̅]${NC}"
fi

PRETTY_FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
[ -z "$PRETTY_FILES" ] && exit 0

# Prettify all selected files
echo "$PRETTY_FILES" | xargs ./node_modules/.bin/prettier --ignore-unknown --write

# Add back the modified/prettified files to staging
echo "$PRETTY_FILES" | xargs git add

echo "${GREEN} ✔ Prettier executed successfully [̲̅$̲̅(̲̅ ͡° ͜ʖ ͡°̲̅)̲̅$̲̅]${NC}"

exit 0