# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Docker Build and Publish
run-name: ${{ github.actor }} - Docker build and push to ghcr.io registry
on:
  push:
    branches: ['release']

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image for UI builder
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.builder
          push: true
          tags: ${{ github.repository }}-builder:${{ github.sha }},${{ github.repository }}-builder:${{ github.ref_name }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ github.repository }}:${{ github.sha }},${{ github.repository }}:${{ github.ref_name }}
