name: ES Lint
run-name: ${{ github.actor }} - Perform ES Lint
on: [pull_request]
jobs:
  code-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '19.2'
      - run: npm i --force
      - run: npm run lint
